-- Create database
CREATE DATABASE IF NOT EXISTS student_management;
USE student_management;

-- Users table
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

-- Students table
CREATE TABLE IF NOT EXISTS students (
    student_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    department VARCHAR(50) NOT NULL,
    semester VARCHAR(10) NOT NULL,
    email VARCHAR(100) NOT NULL,
    image_url VARCHAR(255) NOT NULL
);

-- Insert 100 sample students
INSERT INTO students (name, department, semester, email, image_url) VALUES
('Aarav Sharma', 'Computer Science', '1', 'aarav.sharma@example.com', 'images/avatar1.png'),
('Priya Singh', 'Information Technology', '2', 'priya.singh@example.com', 'images/avatar2.png'),
('Rahul Verma', 'Computer Science', '3', 'rahul.verma@example.com', 'images/avatar3.png'),
('Sneha Patel', 'Information Technology', '4', 'sneha.patel@example.com', 'images/avatar4.png'),
('Vikram Gupta', 'Computer Science', '5', 'vikram.gupta@example.com', 'images/avatar5.png'),
('Anjali Mehra', 'Information Technology', '6', 'anjali.mehra@example.com', 'images/avatar6.png'),
('Rohan Das', 'Computer Science', '7', 'rohan.das@example.com', 'images/avatar7.png'),
('Kavya Nair', 'Information Technology', '8', 'kavya.nair@example.com', 'images/avatar8.png'),
('Manav Joshi', 'Computer Science', '1', 'manav.joshi@example.com', 'images/avatar9.png'),
('Isha Kapoor', 'Information Technology', '2', 'isha.kapoor@example.com', 'images/avatar10.png'),
('Amit Sinha', 'Computer Science', '3', 'amit.sinha@example.com', 'images/avatar11.png'),
('Neha Reddy', 'Information Technology', '4', 'neha.reddy@example.com', 'images/avatar12.png'),
('Siddharth Rao', 'Computer Science', '5', 'siddharth.rao@example.com', 'images/avatar13.png'),
('Pooja Jain', 'Information Technology', '6', 'pooja.jain@example.com', 'images/avatar14.png'),
('Yash Malhotra', 'Computer Science', '7', 'yash.malhotra@example.com', 'images/avatar15.png'),
('Riya Sen', 'Information Technology', '8', 'riya.sen@example.com', 'images/avatar16.png'),
('Arjun Pillai', 'Computer Science', '1', 'arjun.pillai@example.com', 'images/avatar17.png'),
('Meera Iyer', 'Information Technology', '2', 'meera.iyer@example.com', 'images/avatar18.png'),
('Karan Singh', 'Computer Science', '3', 'karan.singh@example.com', 'images/avatar19.png'),
('Simran Kaur', 'Information Technology', '4', 'simran.kaur@example.com', 'images/avatar20.png'),
('Dev Patel', 'Computer Science', '5', 'dev.patel@example.com', 'images/avatar21.png'),
('Ayesha Khan', 'Information Technology', '6', 'ayesha.khan@example.com', 'images/avatar22.png'),
('Nikhil Jain', 'Computer Science', '7', 'nikhil.jain@example.com', 'images/avatar23.png'),
('Tanya Bhatia', 'Information Technology', '8', 'tanya.bhatia@example.com', 'images/avatar24.png'),
('Saurabh Mishra', 'Computer Science', '1', 'saurabh.mishra@example.com', 'images/avatar25.png'),
('Divya Agarwal', 'Information Technology', '2', 'divya.agarwal@example.com', 'images/avatar26.png'),
('Harsh Vardhan', 'Computer Science', '3', 'harsh.vardhan@example.com', 'images/avatar27.png'),
('Shreya Ghosh', 'Information Technology', '4', 'shreya.ghosh@example.com', 'images/avatar28.png'),
('Aditya Roy', 'Computer Science', '5', 'aditya.roy@example.com', 'images/avatar29.png'),
('Pallavi Desai', 'Information Technology', '6', 'pallavi.desai@example.com', 'images/avatar30.png'),
('Rajat Kapoor', 'Computer Science', '7', 'rajat.kapoor@example.com', 'images/avatar31.png'),
('Nisha Dubey', 'Information Technology', '8', 'nisha.dubey@example.com', 'images/avatar32.png'),
('Sanket Kulkarni', 'Computer Science', '1', 'sanket.kulkarni@example.com', 'images/avatar33.png'),
('Aditi Sharma', 'Information Technology', '2', 'aditi.sharma@example.com', 'images/avatar34.png'),
('Gaurav Yadav', 'Computer Science', '3', 'gaurav.yadav@example.com', 'images/avatar35.png'),
('Rashmi Menon', 'Information Technology', '4', 'rashmi.menon@example.com', 'images/avatar36.png'),
('Vivek Singh', 'Computer Science', '5', 'vivek.singh@example.com', 'images/avatar37.png'),
('Sana Shaikh', 'Information Technology', '6', 'sana.shaikh@example.com', 'images/avatar38.png'),
('Parth Patel', 'Computer Science', '7', 'parth.patel@example.com', 'images/avatar39.png'),
('Ira Bhatt', 'Information Technology', '8', 'ira.bhatt@example.com', 'images/avatar40.png'),
('Rudra Chatterjee', 'Computer Science', '1', 'rudra.chatterjee@example.com', 'images/avatar41.png'),
('Maya Nambiar', 'Information Technology', '2', 'maya.nambiar@example.com', 'images/avatar42.png'),
('Kabir Sethi', 'Computer Science', '3', 'kabir.sethi@example.com', 'images/avatar43.png'),
('Ananya Rao', 'Information Technology', '4', 'ananya.rao@example.com', 'images/avatar44.png'),
('Dhruv Mehta', 'Computer Science', '5', 'dhruv.mehta@example.com', 'images/avatar45.png'),
('Srishti Singh', 'Information Technology', '6', 'srishti.singh@example.com', 'images/avatar46.png'),
('Aman Jain', 'Computer Science', '7', 'aman.jain@example.com', 'images/avatar47.png'),
('Bhavya Shah', 'Information Technology', '8', 'bhavya.shah@example.com', 'images/avatar48.png'),
('Tanvi Deshmukh', 'Computer Science', '1', 'tanvi.deshmukh@example.com', 'images/avatar49.png'),
('Raghav Bansal', 'Information Technology', '2', 'raghav.bansal@example.com', 'images/avatar50.png'),
('Sanya Kapoor', 'Computer Science', '3', 'sanya.kapoor@example.com', 'images/avatar51.png'),
('Aarohi Joshi', 'Information Technology', '4', 'aarohi.joshi@example.com', 'images/avatar52.png'),
('Kunal Sood', 'Computer Science', '5', 'kunal.sood@example.com', 'images/avatar53.png'),
('Lavanya Iyer', 'Information Technology', '6', 'lavanya.iyer@example.com', 'images/avatar54.png'),
('Pranav Reddy', 'Computer Science', '7', 'pranav.reddy@example.com', 'images/avatar55.png'),
('Ishita Sharma', 'Information Technology', '8', 'ishita.sharma@example.com', 'images/avatar56.png'),
('Arnav Singh', 'Computer Science', '1', 'arnav.singh@example.com', 'images/avatar57.png'),
('Mitali Shah', 'Information Technology', '2', 'mitali.shah@example.com', 'images/avatar58.png'),
('Siddhi Patel', 'Computer Science', '3', 'siddhi.patel@example.com', 'images/avatar59.png'),
('Ritvik Nair', 'Information Technology', '4', 'ritvik.nair@example.com', 'images/avatar60.png'),
('Ayaan Khan', 'Computer Science', '5', 'ayaan.khan@example.com', 'images/avatar61.png'),
('Jhanvi Mehta', 'Information Technology', '6', 'jhanvi.mehta@example.com', 'images/avatar62.png'),
('Rudraksh Sharma', 'Computer Science', '7', 'rudraksh.sharma@example.com', 'images/avatar63.png'),
('Sakshi Agarwal', 'Information Technology', '8', 'sakshi.agarwal@example.com', 'images/avatar64.png'),
('Yuvraj Singh', 'Computer Science', '1', 'yuvraj.singh@example.com', 'images/avatar65.png'),
('Aastha Gupta', 'Information Technology', '2', 'aastha.gupta@example.com', 'images/avatar66.png'),
('Ritesh Kumar', 'Computer Science', '3', 'ritesh.kumar@example.com', 'images/avatar67.png'),
('Nandini Rao', 'Information Technology', '4', 'nandini.rao@example.com', 'images/avatar68.png'),
('Shivam Tiwari', 'Computer Science', '5', 'shivam.tiwari@example.com', 'images/avatar69.png'),
('Aarushi Jain', 'Information Technology', '6', 'aarushi.jain@example.com', 'images/avatar70.png'),
('Kartik Sharma', 'Computer Science', '7', 'kartik.sharma@example.com', 'images/avatar71.png'),
('Rhea Sen', 'Information Technology', '8', 'rhea.sen@example.com', 'images/avatar72.png'),
('Aryan Verma', 'Computer Science', '1', 'aryan.verma@example.com', 'images/avatar73.png'),
('Saanvi Desai', 'Information Technology', '2', 'saanvi.desai@example.com', 'images/avatar74.png'),
('Dhruvi Shah', 'Computer Science', '3', 'dhruvi.shah@example.com', 'images/avatar75.png'),
('Vivaan Nair', 'Information Technology', '4', 'vivaan.nair@example.com', 'images/avatar76.png'),
('Aadhya Singh', 'Computer Science', '5', 'aadhya.singh@example.com', 'images/avatar77.png'),
('Reyansh Gupta', 'Information Technology', '6', 'reyansh.gupta@example.com', 'images/avatar78.png'),
('Anvi Mehra', 'Computer Science', '7', 'anvi.mehra@example.com', 'images/avatar79.png'),
('Vihaan Reddy', 'Information Technology', '8', 'vihaan.reddy@example.com', 'images/avatar80.png'),
('Aarav Patel', 'Computer Science', '1', 'aarav.patel@example.com', 'images/avatar81.png'),
('Myra Sharma', 'Information Technology', '2', 'myra.sharma@example.com', 'images/avatar82.png'),
('Advait Singh', 'Computer Science', '3', 'advait.singh@example.com', 'images/avatar83.png'),
('Kiara Nair', 'Information Technology', '4', 'kiara.nair@example.com', 'images/avatar84.png'),
('Arush Gupta', 'Computer Science', '5', 'arush.gupta@example.com', 'images/avatar85.png'),
('Navya Iyer', 'Information Technology', '6', 'navya.iyer@example.com', 'images/avatar86.png'),
('Kabir Sharma', 'Computer Science', '7', 'kabir.sharma@example.com', 'images/avatar87.png'),
('Aanya Mehta', 'Information Technology', '8', 'aanya.mehta@example.com', 'images/avatar88.png'),
('Ishaan Desai', 'Computer Science', '1', 'ishaan.desai@example.com', 'images/avatar89.png'),
('Aarohi Shah', 'Information Technology', '2', 'aarohi.shah@example.com', 'images/avatar90.png'),
('Vivaan Singh', 'Computer Science', '3', 'vivaan.singh@example.com', 'images/avatar91.png'),
('Anaya Reddy', 'Information Technology', '4', 'anaya.reddy@example.com', 'images/avatar92.png'),
('Ayaan Mehra', 'Computer Science', '5', 'ayaan.mehra@example.com', 'images/avatar93.png'),
('Saanvi Sharma', 'Information Technology', '6', 'saanvi.sharma@example.com', 'images/avatar94.png'),
('Reyansh Patel', 'Computer Science', '7', 'reyansh.patel@example.com', 'images/avatar95.png'),
('Aadhya Gupta', 'Information Technology', '8', 'aadhya.gupta@example.com', 'images/avatar96.png'),
('Vihaan Mehta', 'Computer Science', '1', 'vihaan.mehta@example.com', 'images/avatar97.png'),
('Anvi Sharma', 'Information Technology', '2', 'anvi.sharma@example.com', 'images/avatar98.png'),
('Arjun Desai', 'Computer Science', '3', 'arjun.desai@example.com', 'images/avatar99.png'),
('Myra Singh', 'Information Technology', '4', 'myra.singh@example.com', 'images/avatar100.png'); 